### ISSUE TITLE
How do I install this in SFDC

### ISSUE THREAD

**Issue by Aghanomics** [alonkama/ForecastingQuotaAttainmentLightningComponent#1]
I want to give you guys a 5 star review, would greatly appreciate your help!

**Comment by alonkama** [comment]
Go to https://appexchange.salesforce.com/listingDetail?listingId=a0N30000000q66kEAA and install it using your SFDC admin credentials. You should then be able to use Lightning App Builder to drop this component into your page.

**Comment by Aghanomics** [comment]
I've been struggling with this (I'm not very technical). Any chance we can hop on a call? Will gladly give you 5 stars if you can!
