### ISSUE TITLE
Can't find app?

### ISSUE THREAD

**Issue by shurley929** [alonkama/ForecastingQuotaAttainmentLightningComponent#3]
I downloaded and installed the app, I can see it in my 'Installed Packages' under setup--but cannot find it in my App Manager where my other apps appear as buttons. 

Help?

**Comment by alonkama** [comment]
This is a Lightning Component - not an app. You may find it in the sidebar
of the Lightning App Builder as a component that can be dragged onto a page.

**Comment by shurley929** [comment]
I see now, thank you!

Shelley Hurley
Sales Operations Manager
P 918.710.4618 | C  918.344.0724 | F 918.749.1987
[Brief-Media]
2021 S Lewis Ave. Suite 760 | Tulsa, OK 74104
cliniciansbrief.com<http://www.cliniciansbrief.com/> | veterinaryteambrief<http://www.veterinaryteambrief.com/>.com |
plumbstherapeuticsbrief.com<http://www.plumbstherapeuticsbrief.com/> | plumbsveterinarydrugs.com<https://www.plumbsveterinarydrugs.com/> |
newyorkvet.com
Print & Digital Specifications<http://cliniciansbrief.com/sites/default/files/uploads/BriefMedia_SpecsDocumentation.pdf>


This email and any attachments are proprietary and confidential information of Brief Media. No part of this email and its attachments may be shared or distributed in any manner without the prior written consent of Educational Concepts, LLC dba Brief Media. If you have received this transmission in error, please notify by reply e-mail and destroy the original transmission and its attachments. Thank you.
